name: Label issues

permissions:
  issues: write

on:
  issues:
    types:
      - opened

jobs:
  label_issues:
    uses: cap-java/.github/.github/workflows/issue.yml@9fc20a42d6556aa4cab5fcfe0f58002aa4851103 # main
