name: Label issues

permissions:
  issues: write

on:
  issues:
    types:
      - opened

jobs:
  label_issues:
    uses: cap-java/.github/.github/workflows/issue.yml@296573b55e906f5c77a1855bcfe4285cbbc5cac4 # main
