name: Prevent "New" Label on Issues

permissions:
  issues: write

on:
  issues:
    types: [labeled]

jobs:
  remove_new_label:
    uses: cap-java/.github/.github/workflows/prevent-issue-labeling.yml@9fc20a42d6556aa4cab5fcfe0f58002aa4851103 # main
