name: Prevent "New" Label on Issues

permissions:
  issues: write

on:
  issues:
    types: [labeled]

jobs:
  remove_new_label:
    uses: cap-java/.github/.github/workflows/prevent-issue-labeling.yml@main
