name: Test CAP Projects

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [21,25]
    name: Test (Java ${{ matrix.java-version }})
    
    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

    - name: Test CAP Projects
      uses: ./.github/actions/test
      with:
        java-version: ${{ matrix.java-version }}
        node-version: '22'
